version: '3'

volumes:
  viole_db_dco: {}

services:
  db:
    image: mysql:5.7
    volumes:
      - viole_db_dco:/var/lib/mysql/data
    restart: always
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: viole
  backend:
    build:
      context: .
      dockerfile: Dockerfile-compose-backend
    environment:
      - ENV=dev
      - DB_URL=mysql://root:password@${viole-db}:3306/viole
    expose:
      - 8000
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./:/app/
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile-compose-scheduler
    environment:
      - HOST=http://${viole-backend}:8000
    volumes:
      - ./:/app/
    command:
      - bash
      - -c
      - |
        python scheduler.py
