version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: viole
  backend:
    build:
      context: .
      dockerfile: ./compose/Dockerfile-dev
    environment:
      - ENV=dev
      - DB_URL=mysql://root:password@${viole-db}:3306/viole
    expose:
      - 8000
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./:/app/
    links:
      - db:viole-db